### ISSUE TITLE
500 Error when using on modx 2.3

### ISSUE THREAD

**Issue by joeke** [modxcms/oauth2-server#4]
When using in combination with modx 2.3.3 or 2.3.6 the interact snippet generates a 500 error:

`PHP Fatal error:  Call to undefined method modTransportProvider_mysql::latest() in /my-website/public/core/components/modxcontrolclient/model/modxcontrolclient/modxcontrolclient.class.php on line 580`

**Comment by sepiariver** [comment]
Sorry @joeke which one is the "interact" snippet please?

Also it looks like the error you posted is for a package with namespace "modxcontrolclient", but this is the repo for oauth2-server...are you sure it's the right repo for this issue?

Thanks, YJ
